### ISSUE TITLE
使用python爬取新闻

### ISSUE THREAD

**Issue by jakefeng** [TaiyouDong/NewsAggregationWebsiteKoa2#2]
https://github.com/TaiyouDong/NewsSpider

你的项目中的地址是个404，找不到地址，MongoDB数据库里面的数据结构是什么，我加载不到新闻出来，想从你这个项目中，体验一下新搜索，MongoDB里面的数据字段是怎么设计的

**Comment by Uyouii** [comment]
嗷，之前因为有些项目的原因删除掉了，你还需要嘛，我放到网盘上算了。

**Comment by Uyouii** [comment]
我晚上回去更新下项目，不知道为什么之前的issue没有发送到我的邮箱，问题没有看到

**Comment by Uyouii** [comment]
already done

**Comment by jakefeng** [comment]
我已经收到你的邮件
